# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

#container:
#  image: 'gubraun/coverity:2019.06'
#  endpoint: gubraun-docker
#  options: --hostname build-vm --mac-address 02:42:ac:11:00:03

steps:
#- script: |
#    cov-analyze --ident
#    cov-configure --config coverity_config.xml --gcc
#  displayName: 'Configure Coverity'

#- script: cov-build --config coverity_config.xml --dir idir gcc -o hello hello.c
- script: make
  displayName: 'Compile C source file'
  
-script: |
   wget https://sipse.polaris.synopsys.com/api/tools/polaris_cli-linux64.zip
   unzip polaris_cli-linux64-1.5.4628.zip
   ./polaris_cli-linux64-1.5.4628/bin/polaris analyze -w
   

#- script: cov-analyze --dir idir 
#  displayName: 'Run Coverity analysis'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
