# This is a basic workflow to help you get started with Actions

name: Coverity

# Controls when the workflow will run
on: workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  analyze:
    name: Analyze
    runs-on: self-hosted
    env:
      COVERITY_TOOL_HOME: /opt/cov-analysis-linux64-2021.06
    steps:
      - uses: actions/checkout@v2
      - name: Coverity
        run: |
          $COVERITY_TOOL_HOME/bin/cov-build --dir idir make
          $COVERITY_TOOL_HOME/bin/cov-analyze --dir idir --ticker-mode none --all --enable-audit-mode --strip-path $PWD
          $COVERITY_TOOL_HOME/bin/cov-format-errors --dir idir --json-output-v7 coverity-results.json
      - name: Convert results to SARIF
        run: |
          $COVERITY_TOOL_HOME/node/bin/node $COVERITY_TOOL_HOME/SARIF/cov-format-sarif-for-github.js -i coverity-results.json -r gubraun/tinyxml2 -c gubraun/tinyxml2 `pwd` `git rev-parse HEAD` -o coverity-results.sarif
      - name: Upload SARIF file to GitHub UI
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: coverity-results.sarif
